# 定时任务中心配置信息
job:
  server:
    enabled: true
    # 校验令牌，和服务器保持一致
    accessToken: accessToken
    username: admin
    password: 123456
    jobGroup: 1
    # 定时任务中心地址，通过环境变量取值，（预发布环境需填写预发布的域名，不然会调到开发环境的服务）
    addresses: http://127.0.0.1:8880/xxl-job-admin




